{
 "title": "RDS Resource Utilisation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilisation under 10% ",
   "type": "table",
   "gridPos": { "h": 25, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum by (cpu,node_name) (max_over_time(node_cpu_average{mode!=\"idle\",mode!=\"iowait\",cpu!=\"All\"}[7d])) < 10)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation under 10% - 20% ",
   "type": "table",
   "gridPos": { "h": 25, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum by (cpu,node_name) (max_over_time(node_cpu_average{mode!=\"idle\",mode!=\"iowait\",cpu!=\"All\"}[1d])) > 10 < 20)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation under 20% - 30% ",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum by (cpu,node_name) (max_over_time(node_cpu_average{mode!=\"idle\",mode!=\"iowait\",cpu!=\"All\"}[1d])) > 20 < 30)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation > 30%",
   "type": "table",
   "gridPos": { "h": 25, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sort_desc(sum by (cpu,node_name) (max_over_time(node_cpu_average{mode!=\"idle\",mode!=\"iowait\",cpu!=\"All\"}[1d])) > 30)",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}